title: "Ima Bin | Product Designer Portfolio"
description: "Data-driven Product Designer / Product Owner"
lang: ko-KR

collections:
  projects:
    output: true
    permalink: /projects/:name/

navigation:
  - title_ko: "Portfolio"
    title_en: "Portfolio"
    url: "/portfolio/"
  - title_ko: "Career"
    title_en: "Resume"
    url: "/resume/"
  - title_ko: "About"
    title_en: "About"
    url: "/about/"
  - title_ko: "Blog"
    title_en: "Blog"
    url: "/blog/"
  - title_ko: "Contact"
    title_en: "Contact"
    url: "/contact/"
